version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Riyadh
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "chore(actions)"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Asia/Riyadh
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: "chore(pip)"
    groups:
      python-minor-patch:
        update-types:
          - minor
          - patch
