#!/usr/bin/env python3
"""
routes/top10_investments.py
------------------------------------------------------------
TOP 10 INVESTMENTS ROUTER — v1.0.0 (ONE SOURCE OF TRUTH / LIVE / SCHEMA-FIRST)

Phase C / Script #5

Fix objective
- ✅ Top_10_Investments must be generated by a dedicated route (not generic sheet-rows).
- ✅ Uses core.analysis.top10_selector as the SINGLE source of truth.
- ✅ Live mode (engine /quotes-based), no snapshot dependency.
- ✅ Returns schema-aligned rows (83 cols: 80 canonical + 3 Top10 extras).
- ✅ Startup-safe: no network calls at import time.

Endpoints
- POST /v1/top10/investments
- POST /v1/top10/top-10-investments        (alias)
- POST /v1/top10/top10                     (alias)
- GET  /v1/top10/health

Request body (flexible)
{
  "criteria": {...},          # optional dict
  "limit": 10,                # optional
  "mode": "",                 # optional engine mode hint
  ...                         # criteria may also be provided at top-level
}

Response
{
  "status": "success",
  "page": "Top_10_Investments",
  "headers": [...],
  "keys": [...],
  "rows": [...],
  "rows_matrix": [...],       # optional
  "meta": {...}
}
"""

from __future__ import annotations

import logging
import os
import time
import uuid
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Body, Header, HTTPException, Query, Request, status
from fastapi.encoders import jsonable_encoder

logger = logging.getLogger("routes.top10_investments")
logger.addHandler(logging.NullHandler())

TOP10_ROUTE_VERSION = "1.0.0"

router = APIRouter(prefix="/v1/top10", tags=["top10"])


# -----------------------------------------------------------------------------
# Auth (best-effort, consistent with other routers)
# -----------------------------------------------------------------------------
try:
    from core.config import auth_ok, get_settings_cached  # type: ignore
except Exception:
    auth_ok = None  # type: ignore

    def get_settings_cached(*args: Any, **kwargs: Any) -> Any:  # type: ignore
        return None


def _extract_auth_token(*, token_query: Optional[str], x_app_token: Optional[str], authorization: Optional[str]) -> str:
    auth_token = (x_app_token or "").strip()
    if authorization and authorization.strip().lower().startswith("bearer "):
        auth_token = authorization.strip().split(" ", 1)[1].strip()

    if token_query and not auth_token:
        allow_query = False
        try:
            settings = get_settings_cached()
            allow_query = bool(getattr(settings, "allow_query_token", False))
        except Exception:
            allow_query = False
        if allow_query:
            auth_token = token_query.strip()

    return auth_token


def _require_auth_or_401(*, token_query: Optional[str], x_app_token: Optional[str], authorization: Optional[str]) -> None:
    if auth_ok is None:
        return
    auth_token = _extract_auth_token(token_query=token_query, x_app_token=x_app_token, authorization=authorization)
    if not auth_ok(
        token=auth_token,
        authorization=authorization,
        headers={"X-APP-TOKEN": x_app_token, "Authorization": authorization},
    ):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token")


# -----------------------------------------------------------------------------
# Engine accessor (lazy + safe)
# -----------------------------------------------------------------------------
async def _get_engine(request: Request) -> Optional[Any]:
    try:
        st = getattr(request.app, "state", None)
        if st and getattr(st, "engine", None):
            return st.engine
    except Exception:
        pass

    for modpath in ("core.data_engine_v2", "core.data_engine"):
        try:
            mod = __import__(modpath, fromlist=["get_engine"])
            get_engine = getattr(mod, "get_engine", None)
            if callable(get_engine):
                eng = get_engine()
                if hasattr(eng, "__await__"):
                    eng = await eng
                return eng
        except Exception:
            continue
    return None


def _safe_int(v: Any, default: int) -> int:
    try:
        x = int(float(v))
        return x
    except Exception:
        return default


def _coerce_bool(v: Any, default: bool = False) -> bool:
    if isinstance(v, bool):
        return v
    if isinstance(v, str):
        return v.strip().lower() in {"1", "true", "yes", "y", "on"}
    return default


def _flatten_criteria(body: Dict[str, Any]) -> Dict[str, Any]:
    """
    Accept criteria from:
      - body["criteria"] dict (preferred)
      - plus top-level keys (override), to match your cross-route convention
    """
    crit: Dict[str, Any] = {}
    if isinstance(body.get("criteria"), dict):
        crit.update(body["criteria"])

    # allow common top-level overrides
    for k in (
        "pages_selected",
        "pages",
        "invest_period_days",
        "min_expected_roi",
        "max_risk_score",
        "min_confidence",
        "min_ai_confidence",
        "min_volume",
        "use_liquidity_tiebreak",
        "enforce_risk_confidence",
        "top_n",
        "enrich_final",
    ):
        if k in body and body.get(k) is not None:
            crit[k] = body.get(k)
    return crit


def _rows_to_matrix(rows: List[Dict[str, Any]], keys: List[str]) -> List[List[Any]]:
    return [[r.get(k) for k in keys] for r in rows]


# -----------------------------------------------------------------------------
# Health
# -----------------------------------------------------------------------------
@router.get("/health")
async def top10_health(request: Request) -> Dict[str, Any]:
    engine = await _get_engine(request)
    return jsonable_encoder(
        {
            "status": "ok" if engine else "degraded",
            "version": TOP10_ROUTE_VERSION,
            "engine_available": bool(engine),
            "engine_type": type(engine).__name__ if engine else "none",
        }
    )


# -----------------------------------------------------------------------------
# Main endpoint (dedicated Top10 generator)
# -----------------------------------------------------------------------------
@router.post("/investments")
@router.post("/top-10-investments")
@router.post("/top10")
async def top10_investments(
    request: Request,
    body: Dict[str, Any] = Body(default_factory=dict),
    mode: str = Query(default="", description="Optional mode hint for engine/provider"),
    include_matrix: Optional[bool] = Query(default=None, description="Return rows_matrix for legacy clients"),
    limit: Optional[int] = Query(default=None, ge=1, le=50, description="How many items to return (1..50)"),
    token: Optional[str] = Query(default=None, description="Auth token (query only if allowed)"),
    x_app_token: Optional[str] = Header(default=None, alias="X-APP-TOKEN"),
    authorization: Optional[str] = Header(default=None, alias="Authorization"),
    x_request_id: Optional[str] = Header(default=None, alias="X-Request-ID"),
) -> Dict[str, Any]:
    """
    Dedicated Top_10_Investments page generator (schema-aligned).
    """
    t0 = time.perf_counter()
    _require_auth_or_401(token_query=token, x_app_token=x_app_token, authorization=authorization)
    request_id = x_request_id or getattr(request.state, "request_id", None) or str(uuid.uuid4())

    engine = await _get_engine(request)
    if engine is None:
        raise HTTPException(status_code=503, detail="Data engine unavailable")

    # limit selection order: query param > body > default
    eff_limit = limit if isinstance(limit, int) else _safe_int(body.get("limit") or body.get("top_n") or 10, 10)
    eff_limit = max(1, min(50, int(eff_limit)))

    include_matrix_final = include_matrix if isinstance(include_matrix, bool) else _coerce_bool(body.get("include_matrix"), True)

    criteria = _flatten_criteria(body or {})
    criteria["top_n"] = eff_limit  # enforce

    # Call the ONE source of truth
    try:
        from core.analysis.top10_selector import build_top10_rows  # type: ignore
    except Exception as e:
        raise HTTPException(
            status_code=503,
            detail={"error": "Top10 selector unavailable", "detail": f"{type(e).__name__}: {e}"},
        )

    try:
        payload = await build_top10_rows(engine=engine, criteria=criteria, limit=eff_limit, mode=mode or "")
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Top10 generation failed", "detail": f"{type(e).__name__}: {e}"},
        )

    if not isinstance(payload, dict):
        raise HTTPException(status_code=500, detail="Top10 generation returned invalid payload")

    headers = payload.get("headers") or []
    keys = payload.get("keys") or []
    rows = payload.get("rows") or []

    if not isinstance(headers, list):
        headers = []
    if not isinstance(keys, list):
        keys = []
    if not isinstance(rows, list):
        rows = []

    # Ensure schema-aligned projection (keys define order)
    norm_rows: List[Dict[str, Any]] = []
    if keys:
        for r in rows:
            if isinstance(r, dict):
                norm_rows.append({k: r.get(k, None) for k in keys})
    else:
        for r in rows:
            if isinstance(r, dict):
                norm_rows.append(dict(r))

    # hard cap to eff_limit (just in case)
    norm_rows = norm_rows[:eff_limit]

    meta = payload.get("meta") if isinstance(payload.get("meta"), dict) else {}
    meta = dict(meta)
    meta.update(
        {
            "route_version": TOP10_ROUTE_VERSION,
            "request_id": request_id,
            "limit": eff_limit,
            "mode": mode,
            "duration_ms": round((time.perf_counter() - t0) * 1000.0, 3),
            "schema_aligned": bool(keys),
        }
    )

    return jsonable_encoder(
        {
            "status": payload.get("status") or "success",
            "page": "Top_10_Investments",
            "headers": headers,
            "keys": keys,
            "rows": norm_rows,
            "rows_matrix": _rows_to_matrix(norm_rows, keys) if (include_matrix_final and keys) else None,
            "version": TOP10_ROUTE_VERSION,
            "request_id": request_id,
            "meta": meta,
        }
    )


__all__ = ["router"]
